UPLOAD_FOLDER = '/home/ubuntu/uploads/'
AWS_ACCESS_KEY = 'ADD THIS'
AWS_SECRET_KEY = ADD THIS'
MICROSOFT_KEY = 'ADD THIS'
MICROSOFT_ENTITY_KEY = 'Add This'
SQLALCHEMY_DATABASE_URI = "sqlite:///test.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False
